[build-system]
requires = ['poetry-core>=1.0.0']
build-backend = 'poetry.core.masonry.api'

[tool.poetry]
name = 'climate_indices'
version = '1.1.0'
description = 'Reference implementations of various climate indices typically used for drought monitoring'
authors = ['James Adams <monocongo@gmail.com>']
readme = 'README.md'
classifiers = [
     'Development Status :: 5 - Production/Stable',
     'Intended Audience :: Developers',
     'Intended Audience :: Education',
     'Intended Audience :: Science/Research',
     'License :: OSI Approved :: BSD License',
     'Programming Language :: Python :: 3.8',
     'Programming Language :: Python :: 3.9',
     'Programming Language :: Python :: 3.10',
     'Programming Language :: Python :: 3.11',
     'Topic :: Software Development :: Libraries :: Python Modules',
     'Topic :: Scientific/Engineering :: Atmospheric Science',
     'Topic :: Scientific/Engineering :: Physics'
]
packages = [{include = 'climate_indices', from = 'src'}]

[tool.poetry.dependencies]
dask = '2022.2.0'
numba = '0.57.0'
python = '>=3.8,<3.12'
scipy = '1.9.3'
xarray = '2023.1.0'

[tool.poetry.dev-dependencies]
pytest = '*'

[tool.pytest.ini_options]
filterwarnings = [
    'ignore::FutureWarning',
]

[project.scripts]
process_climate_indices = 'climate_indices.__main__:main'
spi = 'climate_indices.__spi__:main'

[project.urls]
'Homepage' = 'https://github.com/monocongo/climate_indices'
'Bug Tracker' = 'https://github.com/monocongo/climate_indices/issues'
